### ISSUE TITLE
Fatal error:  when using google autentification

### ISSUE THREAD

**Issue by ittrium79** [kanboard/plugin-google-auth#2]
**When i try to login by google autentification, i get this error:** 
Fatal error: Can't inherit abstract function Kanboard\Core\User\UserProviderInterface::getExternalIdColumn() (previously declared abstract in Kanboard\User\OAuthUserProvider) in /var/www/morrison_pr/data/www/pr.morrison.com.ua/kanboard/app/User/OAuthUserProvider.php on line 14

Linux 2.6.32-042stab113.11
kanboard v1.0.30
database mysql v5.1.73
PHP v5.3.3

**Comment by fguillot** [comment]
This compatibility issue with PHP 5.3 is now fixed in the development branch of Kanboard.

If you don't want to wait the next release, the fix is here: https://github.com/fguillot/kanboard/commit/3813acf199a5873c6f5f8ff945e8a83ea745b8af#diff-1e4968f2afc5a4ef15d734682ab12bc3L16 (remove the line `abstract public function getExternalIdColumn();`)

Thanks!

**Comment by ittrium79** [comment]
Thanks!!! It works!
